name: node
#The name is yours to choose
type: nodejs
#Type of the runtime
web:
  commands:
    start: "PM2_HOME=/app/run pm2 start index.js --no-daemon"
    #command used to start your daemon. Needs to run in the foreground
    #in this setup you will find your application's logs
    #with stdout and stderr in /app/run/logs
relationships:
  first_db: "db:mongodb"
dependencies:
  nodejs:
    pm2: "^0.15.10"
hooks:
    #no need to run npm install. If a package.json is found, it runs 
    #automatically
    build: |
      gulp
mounts:
  # these are the R/W mounts
  "/run": "shared:files/run"
disk: 512
# Disk size for app-server