name: node
#The name is yours to choose
type: nodejs
#Type of the runtime
web:
  commands:
    start: "NODE_ENV=production node index.js --singleProcess"
    #command used to start your daemon. Needs to run in the foreground
    #in this setup you will find your application's logs
    #with stdout and stderr in /app/run/logsw
relationships:
  first_db: "db:mongodb"
dependencies:
  nodejs:
    gulp: "latest"
hooks:
    #no need to run npm install. If a package.json is found, it runs 
    #automatically
    build: |
      gulp cssmin
      gulp uglify
mounts:
  # these are the R/W mounts
  "/run": "shared:files/run"
disk: 512
# Disk size for app-server